"""Mark all existing concept-records as stale with a 'pre-Fase-0' reason.

Background: concept records were generated by an early extractor that did not
write provenance. Their inputs (which RAG-chunks) are unknown. Per Fase 3
(ADR-008) the records will be re-extracted with proper provenance; until then
we mark them as stale so the Fase 0 invariant ("every artefact has provenance")
holds.

Usage:
  python tools/extractie/add_provenance_to_concepts.py
  python tools/extractie/add_provenance_to_concepts.py --force   # overwrite
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from tools.lib.provenance import (  # noqa: E402
    Provenance,
    Tooling,
    now_iso,
    read_provenance,
    write_provenance,
)

CONCEPTS_DIR = ROOT / "data" / "concept_records"
STALE_REASON = "pre-Fase-0; geen provenance; te re-extraheren bij Fase 3"


def add_for_concept(json_path: Path, *, force: bool = False) -> tuple[str, str]:
    if not force and read_provenance(json_path) is not None:
        return "already-has-provenance", ""
    prov = Provenance(
        inputs=[],
        tooling=Tooling(
            pipeline="tools/extractie/concept_extractor.py",
            pipeline_version="pre-Fase-0",
        ),
        generated_at=now_iso(),
        stale=True,
        stale_reason=STALE_REASON,
    )
    write_provenance(json_path, prov)
    return "marked-stale", str(json_path.relative_to(ROOT))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="Overwrite existing provenance")
    args = ap.parse_args()

    targets = sorted(CONCEPTS_DIR.glob("*.json"))
    counts: dict[str, int] = {}
    for t in targets:
        status, detail = add_for_concept(t, force=args.force)
        counts[status] = counts.get(status, 0) + 1
        if status == "marked-stale":
            print(f"  {status:22s}  {detail}")

    print(f"\nScanned {len(targets)} concept records:")
    for status, n in sorted(counts.items()):
        print(f"  {status:22s}  {n}")


if __name__ == "__main__":
    main()
